spring.application.name=News_reading

server.address=0.0.0.0
server.port=${PORT:8080}

# MySQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-21e9ca95-onkarpawar238-31e8.d.aivencloud.com:23430/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
